http://localhost:3000/users

###

POST http://localhost:3000/auth
Content-Type: application/json

{
     "email": "janedoe11@example.com ",
    "name":"Jane Doe11",
    "password": "securepassword",
    "title":"My First Post11",
    "bio":"Software developer and tech enthusiast11.",
    "content":"This is the content of my first post11."
}

###

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
     "email": "janedoe@example.com ",
    "password": "securepassword"
}

###

POST http://localhost:3000/users
Content-Type: application/json

{
     "email": "janedoe9@example.com ",
    "name":"Jane Doe9",
    "password": "securepassword",
    "title":"My First Post9",
    "bio":"Software developer and tech enthusiast9.",
    "content":"This is the content of my first post9."
}

###

PUT http://localhost:3000/posts
    ?id=10
    &published=true
    Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzgsImVtYWlsIjoid2V4ZW1vMkBldnVzZC5jb20iLCJpYXQiOjE3MzY5NTc0NzcsImV4cCI6MTczNjk2MTA3N30.h08sVDP4GRq9C7mJsNgd-mI_qzbdABLrv2QxbbarWC8

###

DELETE http://localhost:3000/posts/40

###

DELETE http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJqYW5lZG9lQGV4YW1wbGUuY29tICIsImlhdCI6MTczNjk2MDY2OSwiZXhwIjoxNzM2OTY0MjY5fQ.oAQWPzsVN28ghf5gZDVeWEZPBarOZ-M860dRKqhOdmU
    