http://localhost:3000/api/users

###

POST http://localhost:3000/api/auth
Content-Type: application/json

{
     "name": "wexemo53 ",
    "email": " wexemo53@evusd.com  ",
    "password":"123456Ab",
    "title":"My First Post53",
    "bio":"Software developer and tech enthusiast53.",
    "content":"This is the content of my first post53."
}

###

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
     "email": "wexemo49@evusd.com ",
    "password": "123456Ab"
}

###

POST http://localhost:3000/api/users
Content-Type: application/json

{
     "email": "janedoe9@example.com ",
    "name":"Jane Doe9",
    "password": "securepassword",
    "title":"My First Post9",
    "bio":"Software developer and tech enthusiast9.",
    "content":"This is the content of my first post9."
}

###

PUT http://localhost:3000/api/posts
    ?id=10
    &published=true
    Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzcsImVtYWlsIjoid2V4ZW1vM0BldnVzZC5jb20iLCJpYXQiOjE3MzY5NjY5NTIsImV4cCI6MTczNjk3MDU1Mn0.-M6fcS-nCaR4fXtequxRaDhjJHcT_pgTXnhtyK-2jIM

###

DELETE http://localhost:3000/api/posts/3

###

DELETE http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJqYW5lZG9lQGV4YW1wbGUuY29tICIsImlhdCI6MTczNjk2MDY2OSwiZXhwIjoxNzM2OTY0MjY5fQ.oAQWPzsVN28ghf5gZDVeWEZPBarOZ-M860dRKqhOdmU

###

DELETE http://localhost:3000/api/users/46/48


    