http://localhost:3000/users

###

POST http://localhost:3000/auth
Content-Type: application/json

{
     "email": "janedoe11@example.com ",
    "name":"Jane Doe11",
    "password": "securepassword",
    "title":"My First Post11",
    "bio":"Software developer and tech enthusiast11.",
    "content":"This is the content of my first post11."
}

###

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
     "email": "janedoe11@example.com ",
    "password": "securepassword"
}

###

POST http://localhost:3000/users
Content-Type: application/json

{
     "email": "janedoe9@example.com ",
    "name":"Jane Doe9",
    "password": "securepassword",
    "title":"My First Post9",
    "bio":"Software developer and tech enthusiast9.",
    "content":"This is the content of my first post9."
}

###

PUT http://localhost:3000/posts
    ?id=10
    &published=true

###

DELETE http://localhost:3000/posts/40
    